### ISSUE TITLE
Add support for Team and User

### ISSUE THREAD

**Issue by pgarbe** [mongodb/mongodbatlas-cloudformation-resources#13]
Please, add support for MongoDB::Atlas::Team and MongoDB::Atlas::User so that user provisioning and team assignment can be automated. This is also needed if you use SAML.

**Comment by themantissa** [comment]
@pgarbe Thank you for the feedback. We'll have the ability to request features specifically for CloudFormation via feedback.mongodb.com once we officially GA this work.  Until then I'll be sure to note both as desired.

**Comment by Zuhairahmed** [comment]
We have refreshed resource and published to AWS CFN Third Party Public Registry in all 22 AWS regions where MongoDB Atlas is currently available in. Including support for MongoDB::Atlas::Teams, feel free to reach out if you need anything else.
