### ISSUE TITLE
Unable to retrieve ConnectionStrings attribute for MongoDB::Atlas::Cluster

### ISSUE THREAD

**Issue by Nitjsefni7** [mongodb/mongodbatlas-cloudformation-resources#163]
### CloudFormation Template 

```
Resources:
  Cluster:
    Properties:
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      BackupEnabled: false
      ClusterType: REPLICASET
      MongoDBMajorVersion: "6.0"
      Name:
        Fn::Sub: ${Environment}-SmartMerchant-Cluster
      PitEnabled: false
      ProjectId:
        Ref: Project
      ReplicationSpecs:
      - AdvancedRegionConfigs:
        - ElectableSpecs:
            EbsVolumeType: PROVISIONED
            InstanceSize: M10
            NodeCount: 3
          Priority: 7
          RegionName: US_EAST_1
        NumShards: 0
      TerminationProtectionEnabled: false
    Type: MongoDB::Atlas::Cluster
    Version: "0.1"

Outputs:
  MongoDBAtlasConnectionStrings:
    Description: Cluster connection strings
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ConnectionStrings
    Value:
      Fn::GetAtt:
      - Cluster
      - ConnectionStrings
```

### Steps to Reproduce
I am using the official public extensions for MongoDB Atlas in CloudFormation and I have successfully deployed all the resources, however when I am trying to output some properties of the cluster, deployment fails.

### Expected Behavior
The output parameters like ConnectionStrings or ClusterState should be available.

### Actual Behavior
I am receiving an error ```Unable to retrieve ConnectionStrings attribute for MongoDB::Atlas::Cluster, with error message The next fields are required ApiKeys.PublicKey ApiKeys.PrivateKey ProjectId Name```

### Additional Context
Secret in Secrets Manager which is created along with the Cluster is present.

**Comment by Nitjsefni7** [comment]
Same case with `Id attribute for MongoDB::Atlas::NetworkPeering`

**Comment by govardhanpagidi** [comment]
@Nitjsefni7, you should be able to read the connection string now.
eg:
    "Outputs": {
        "MongoDBAtlasConnectionStrings": {
            "Description": "Cluster connection strings",
            "Export": {
                "Name": {
                    "Fn::Sub": "${AWS::StackName}-ConnectionStrings"
                }
            },
            "Value": {
                "Fn::GetAtt": [
                    "AtlasCluster",
                    "ConnectionStrings.Standard"
                ]
            }
        }
    }

**Comment by Nitjsefni7** [comment]
I confirm it is working now. 

Any chance for using `GetAtt` to obtain ID for `MongoDB::Atlas::NetworkPeering`?

**Comment by Nitjsefni7** [comment]
You are right, thank you!

**Comment by govardhanpagidi** [comment]
@Nitjsefni7 you should be able to read the PeeringId with out GetAtt, check below. 

"PeerId": {
      "Description": "Id of the network peer",
      "Value" : { "Ref" : "NetworkPeering" }
    }

https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/fa87afd057241b147597ebe64e2f85d7ad021f57/examples/network-peering/peering.json#L58
