### ISSUE TITLE
Build not working with cloudformation-cli-go-plugin v0.1.5

### ISSUE THREAD

**Issue by drpdishant** [mongodb/mongodbatlas-cloudformation-resources#19]
I am trying to build the resource using make command on my machine and it fails with following message.

```
cfn generate
Change message for Go plugin v0.1.3:
Generated models no longer use the types exported in the encoding package.
Your model's fields have been regenerated using standard pointer types (*string, *int, etc) as used in the AWS Go SDK.
The AWS SDK has helper functions that you can use to get and set your model's values.

Make the following changes to your handler code as needed:

* Replace `encoding.New{Type}` with `aws.{Type}`
* Replace `model.{field}.Value()` with `aws.{Type}Value(model.{field})`

Where {Type} is either String, Bool, Int, or Float64 and {field} is any field within your generated model.

Generated files for MongoDB::Atlas::NetworkPeering
env GOOS=linux go build -ldflags="-s -w" -tags="logging callback metrics scheduler" -o bin/handler cmd/main.go
# github.com/mongodb/mongodbatlas-cloudformation-resources/network-peering/cmd/resource
cmd/resource/resource.go:14:73: currentModel.ApiKeys.PublicKey.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:14:115: currentModel.ApiKeys.PrivateKey.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:20:38: currentModel.ProjectId.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:22:41: currentModel.ContainerId.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:25:43: currentModel.AccepterRegionName.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:29:43: currentModel.AwsAccountId.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:33:44: currentModel.RouteTableCidrBlock.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:37:29: currentModel.VpcId.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:41:43: currentModel.ProviderName.Value undefined (type *string has no field or method Value)
cmd/resource/resource.go:57:18: cannot use encoding.NewString(peerResponse.ID) (type *encoding.String) as type *string in assignment
cmd/resource/resource.go:57:18: too many errors
make: *** [Makefile:5: build] Error 2
```

**Comment by themantissa** [comment]
@thetonymaster  fyi, interesting error from the SDK?

@drpdishant we are working to actually provide these as binary, in fact you should be able to see this under releases as of today.

**Comment by azec-pdx** [comment]
I can confirm same issue as @drpdishant when using latest `cloudformation-cli-go-plugin` and `cloudformation-cli` packages.

Environment:

```
> pip show cloudformation-cli-go-plugin

Name: cloudformation-cli-go-plugin
Version: 0.1.5
Summary: UNKNOWN
Home-page: https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/
Author: Amazon Web Services
Author-email: aws-cloudformation-developers@amazon.com
License: Apache License 2.0
Location: /Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: cloudformation-cli, semver
Required-by:
```

and ...

```
> pip show cloudformation-cli

Name: cloudformation-cli
Version: 0.1.3
Summary: UNKNOWN
Home-page: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/
Author: Amazon Web Services
Author-email: aws-cloudformation-developers@amazon.com
License: Apache License 2.0
Location: /Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: pytest, hypothesis, requests, jsonschema, Werkzeug, boto3, PyYAML, colorama, Jinja2
Required-by: cloudformation-cli-go-plugin
```

The problem is that `model.go` files which are autogenerated don't use `"github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"` import anymore and `Model` structs use actual Go types, e.g. `*string` vs `*encoding.String`. 

I tried working out around this with local changes that modify `resource.go` files to not depend on `"github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"`. However I ran into other kind of issues after successfully building and registering resource. One such error was: 

```
2020-05-14 11:14:03 UTC-0700 | MongoDBAtlasProject | CREATE_FAILED | Handler returned SUCCESS but did not return the primaryIdentifier for the physical resource.
```

I will try to register v2 of resources in CloudFormation Registry using go plugin v0.1.5 (env. described above) and try to test few more times with other resources (e.g. Cluster).

**Comment by azec-pdx** [comment]
I would also recommend changing issue title to `Build not working with cloudformation-cli-go-plugin v0.1.5`

**Comment by themantissa** [comment]
@azec-pdx to answer your first question - we do not have any ETA to ensure this can build with most recent versions.  To try to make testing easier we've had the team provide a pre-built release in the repo.    I would see if that moves this along faster. 

We do not have an area for collaboration at this time.   That doesn't preclude having something in the future post-GA.

**Comment by drpdishant** [comment]
@themantissa thanks for the info I'll check the binaries and see if I can make it work.
FYi, I am very much interested to make it work, as currently  we are managing large number of mongodb atlas connections from different applications most of Configs, peering routes, db users, are being created manually, though we also having a team working on configuring lambda function to automate those tasks.

I liked the concept and it will provide a unified experience for managing mongodb atlas Configs from existing cloudformation stack.

**Comment by themantissa** [comment]
Thank you for the feedback @drpdishant !  Let me know how it goes and feel free to reach out directly as well - melissa.plunkett@mongodb.com

**Comment by themantissa** [comment]
Confirmed version of CLI/SDK that build are now noted in the README: 
    AWS CloudFormation CLI 0.1.1
    (Optional - only need if building from source) AWS CloudFormation CLI Go Plugin 0.1.3
    (Optional - only need if building from source) Go 1.12 (to build the provider plugin)

Testing to determine work needed to be able to support latest versions of CLI/Plugin (currently 0.1.3/v0.1.6)
