### ISSUE TITLE
CFN "make schema" command creates JSON schema with empty properties 

### ISSUE THREAD

**Issue by maastha** [mongodb/mongodbatlas-cloudformation-resources#205]
### CloudFormation Template 

```
{
  "definitions": {
    "": {
      "additionalProperties": false
    },
    .
    .
    .
  },
  .,
  .,
  .,
  "properties": {
    "": {},
    .
    .
    .
  },
  .
  .
}

```

### Steps to Reproduce

Generate schema for any API from autogen.

### Expected Behavior

The generated schema should not contain empty properties/values ("") as that causes issues when generating corresponding CFN resource.

### Actual Behavior

CFN "make schema" command creates JSON schema with empty properties.

**Comment by Zuhairahmed** [comment]
bump

**Comment by andreaangiolillo** [comment]
Fixing this issue here https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/420
