### ISSUE TITLE
Project Creation Fails on Cloudformation, while its successfully created on MongoDbAtlas

### ISSUE THREAD

**Issue by drpdishant** [mongodb/mongodbatlas-cloudformation-resources#23]
I used the latest build from releases and tried by applying the example stack for project.
It successfully creates the project on MongoDb Atlas, but on cloudformation it shows create failed and goes into rollback. (also deletion during the rollback doesn't delete the project on MongoDb atlas).
The reason of failure as returned by cloudformation is:
```
Unable to complete request: error creating project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 409 (request "Conflict") A group with name "cloudformation_resource_demo" already exists.
```

**Comment by themantissa** [comment]
@drpdishant thank you for submitting.  @thetonymaster can you take a look here?

**Comment by jasonmimick** [comment]
Hi @drpdishant -

This would be an expected error, since each project names are unique in a given organization. 
Do you have any other logs from the failed stack you could share?

**Comment by drpdishant** [comment]
@jasonmimick No. not having any other logs.

**Comment by jasonmimick** [comment]
Closing - working as expected and not further info
