### ISSUE TITLE
serverless name input regex pattern

### ISSUE THREAD

**Issue by jaypea** [mongodb/mongodbatlas-cloudformation-resources#369]
I tried to create a serverless instance and received an error regarding regex pattern mismatch. 
its defined as 
```
    "Name": {
      "type": "string",
      "description": "Human-readable label that identifies the serverless instance.",
      "maxLength": 64,
      "minLength": 1,
      "pattern": "^([a-zA-Z0-9]([a-zA-Z0-9-]){0,21}(?\u003c!-)([\\w]{0,42}))$"
    },
 ```
 
 which is oddly specific. 
 my input looks like `my-application-name-env-123` which fails. 
 after playing around with regexr.com  i figured, its because of the negative lookbehind `([a-zA-Z0-9-]){0,21}(?\u003c!-)`. which basically rejects `-` characters after the 21st character in the string.
 
 i wonder if this is on purpose as i couldn't find anything in the docs on mongodb.com itself.
 
 Maybe there is some hidden reason behind.
 
 As a user creating names dynamically from applications and cloudformation stacks this forces me to fall back to `([a-zA-Z0-9]{1,64})` and remove all `-` from my input. works, but is less readable in the atlas interface after creation.

**Comment by govardhanpagidi** [comment]
@jaypea the issue has been fixed and available now. Please check.
