### ISSUE TITLE
CFN resources versioning

### ISSUE THREAD

**Issue by suetema** [mongodb/mongodbatlas-cloudformation-resources#383]
Hello

In the last week you've made changes to the atlas cfn resources that change the way the resources are to be created.
These changes are deployed directly to the public third party extensions and this breaks any previously developed stacks.

Are you able to use versioning here so that your breaking changes don't directly impact existing stacks?

**Comment by Zuhairahmed** [comment]
Thanks @suetema for reaching out. We have enabled versioning on each resource (see sample resource below). If you wish to not auto-upgrade to latest MongoDB Atlas CFN resource version follow steps [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html). Hope this helps. 

![image](https://user-images.githubusercontent.com/47370943/222209202-e1bc479a-e3f8-4df8-b254-3f7d9fd20b33.png)

**Comment by suetema** [comment]
Ah, thank you!
