### ISSUE TITLE
enable adding PrivateEndpoint to a specific security group

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#432]
Hello,

I would like to report an issue I encountered while attempting to add a MongoDB Atlas private endpoint using CDK. While the endpoint was successfully created, I noticed that there was no option to add the private endpoint to a non-default security group. In my opinion, it would be beneficial to have an option to add security groups in a similar fashion to subnetIds.

To provide some context, I am using the following code to create the private endpoint:
```
const endpoint = new CfnPrivateEndpoint(scope, 'myPrivateEndpoint', {
            groupId: projectId,
            region: region,
            privateEndpoints: [{
                vpcId: vpc.vpcId,
                subnetIds: vpc.publicSubnets.map(subnet => subnet.subnetId),
            }],
        })
```
I believe this functionality would be a valuable addition to the current implementation since many companies use non-default security groups and would find this issue a complete blocker for creating private endpoints using CDK. 

Thank you for your time and attention to this matter.

**Comment by Zuhairahmed** [comment]
@Adelmar92 ^^ can you take a look " noticed that there was no option to add the private endpoint to a non-default security group"?

**Comment by DamianBis** [comment]
This is a really big thing that is missing from the resources. plenty of organizations that forbid the use of the default security group.

**Comment by Adelmar92** [comment]
hello @mitja-hofer we have made an improvement to private endpoint, we were able to separate the aws private endpoint fron the atlas private endpoint, the atlas private endpoint resource wont be creating aws private endpoints anymore. 
 so the security group you are mentioning, will be managed by the aws VPC private endpoint cloud formation resource (AWS::EC2::VPCEndpoint) ill keep you posted when this is released

**Comment by Zuhairahmed** [comment]
@mitja-hofer new CFN resources were published mainly
