### ISSUE TITLE
SearchIndex: Unable to cast (*string)(0xc0005f04b0) of type *string to map[string]interface{}

### ISSUE THREAD

**Issue by brunomacf** [mongodb/mongodbatlas-cloudformation-resources#482]
### Steps to Reproduce

I have just activated `MongoDB::Atlas::SearchIndex` in AWS with latest version 1.3.0 (i'm already using the cluster, project, user db and other) and now in my CDK code i'm trying to do something like this:

```ts
import { CfnSearchIndex } from '@mongodbatlas-awscdk/search-index';

const mySearchIndex = new CfnSearchIndex(this, 'MySearchIndex', {
  analyzer: 'lucene.standard',
  clusterName: 'my-cluster-name',
  collectionName: 'my-collection',
  database: 'my-db',
  mappings: {
    fields: JSON.stringify({
      text_field: {}
    }),
    dynamic: false,
  },
  profile: 'my-profile',
  projectId: this.project.attrId, // Coming from created project resource created before
  searchAnalyzer: 'lucene.standard'
});
```

### Expected Behavior

Should create the index resource.

### Actual Behavior

Im seeing the following error when i try to run the CDK code:

```
Resource handler returned message: "unable to cast (*string)(0xc0005f04b0) of type *string to map[string]interface{}" (RequestTok
en: 753d68e5-1530-ae23-f455-5306ed80fe55, HandlerErrorCode: InvalidRequest)
```

I already tried to set `mappings.fields` to other stuff like just the field name and even passing the object itself (not converted to string)... notice that i'm passing string there because of typescript which is telling that fields must be a string.

**Comment by andreaangiolillo** [comment]
Hello @brunomacf  👋  
Thank you for raising this issue. I was able to reproduce the issue and I am currently working on resolving it. I will provide an update as soon as possible. In the meantime, would you mind sharing the output of `cdk synth`? This would help me ensure that my fix works as expected. Thank you!

**Comment by andreaangiolillo** [comment]
Hello @brunomacf,
I am pleased to inform you that the issue has been resolved. To ensure that everything is working as intended, please make sure to use v1.1.4 of MongoDB::Atlas::SearchIndex and v1.1.3 of [@mongodbatlas-awscdk/search-index](https://www.npmjs.com/package/@mongodbatlas-awscdk/search-index)

Here is an example of how to set static fields mapping:

```
  const mySearchIndex = new CfnSearchIndex(this, 'MySearchIndex', {
    analyzer: 'lucene.standard',
    clusterName: 'Cluster0',
    collectionName: 'listingsAndReviews',
    database: 'sample_airbnb',
    mappings: {
      fields: [
        "summary:string", 
        "description:string",
        "minimum_nights:number"],
      dynamic: false,
    },
    name: 'mySearchIndexAndreaCDK22',
    profile: 'default',
    projectId: 'projectId',
    searchAnalyzer: 'lucene.standard'
  });
```
 
Please note that the `fields` property is now an array of strings, where each string has the format `FieldName:FieldType`
Thank you.
