### ISSUE TITLE
error getting private connection string from cluster

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#555]
Hello,

I would like to report an issue when getting the private connection string from cluster (via `cluster.connectionStrings.private` or `privateSrv`). The error is thrown if the cluster is just created or the private endpoint has been set up in some previous deploy of the Cloudformation stack.
Error reported by Cloudformation:
`Attribute 'ConnectionStrings.Private' does not exist`

Sample code:
```
const cluster = new CfnCluster(scope, `${props.config.app.appName}AtlasCluster`, {
            projectId: props.projectId,
            name: myName,
            mongoDbMajorVersion: '4.4',
        })
const srvAddress = cluster.connectionStrings.private
```
The `srvAddress` variable is then exported as Cloudformation stack output.

For reference, from `package.json`:
```
...
"dependencies": {
    "@mongodbatlas-awscdk/cluster": "^1.1.5",
    "@mongodbatlas-awscdk/database-user": "^1.1.4",
    "@mongodbatlas-awscdk/network-peering": "^1.1.5",
    "@mongodbatlas-awscdk/private-endpoint": "^1.1.5",
    "@mongodbatlas-awscdk/project": "^1.1.5",
    "@mongodbatlas-awscdk/project-ip-access-list": "^1.1.5",
    ...
},
```
Thank you for your time and attention to this matter.

**Comment by maastha** [comment]
Hi @mitja-hofer 

`private` and `privateSrv` are for Network peering connections. Have you tried using `cluster.connectionStrings.privateEndpoint[]`?

Please let us know if this helps. If not, can you please share more details about your use-case and steps to reproduce?


Ref: https://www.mongodb.com/docs/atlas/reference/api/clusters-create-one/

**privateEndpoint:**
List of private endpoint-aware connection strings that you can use to connect to this cluster through a private endpoint. This parameter returns only if you deployed a private endpoint to all regions to which you deployed this clusters' nodes.

**private:**
Network peering connection strings for each interface Virtual Private Cloud (VPC) endpoint that you configured to connect to this cluster. This connection string uses the mongodb+srv:// protocol. The resource returns this parameter once someone creates a network peering connection to this cluster. This protocol tells the application to look up the host seed list in the Domain Name System (DNS). This list synchronizes with the nodes in a cluster. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to append the seed list or change the URI if the nodes change. Use this URI format if your driver supports it. If it doesn't, use connectionStrings.private. For Amazon Web Services (AWS) clusters, this resource returns this parameter only if you enable custom DNS.
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**privateSrv:**
Network peering connection strings for each interface Virtual Private Cloud (VPC) endpoint that you configured to connect to this cluster. This connection string uses the mongodb+srv:// protocol. The resource returns this parameter when someone creates a network peering connection to this cluster. This protocol tells the application to look up the host seed list in the Domain Name System (DNS). This list synchronizes with the nodes in a cluster. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to append the seed list or change the Uniform Resource Identifier (URI) if the nodes change. Use this Uniform Resource Identifier (URI) format if your driver supports it. If it doesn't, use connectionStrings.private. For Amazon Web Services (AWS) clusters, this parameter returns only if you [enable custom DNS](https://docs.atlas.mongodb.com/reference/api/aws-custom-dns-update/).
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**Comment by mitja-hofer** [comment]
Hi @maastha,

using `cluster.connectionStrings.privateEndpoint` does not work since it is empty.

I am creating a mongo project like so and the functionality does not work. Providing sample code below.

```
const project = new CfnProject(scope, `AtlasProject`, {
            orgId,
            name: myProject,
        })
new CfnProjectIpAccessList(scope, `ProjectIpAccessList`, {
            projectId: project.attrId,
            accessList: [{ ipAddress: '0.0.0.0/0', comment: 'any' }],
        })
const privateEndpoint = new CfnPrivateEndpoint(scope, `PrivateEndpoint`, {
            groupId: project.attrId,
            privateEndpoints: [{
                vpcId: vpc.vpcId,
                subnetIds: vpc.publicSubnets.map(subnet => subnet.subnetId),
            }],
        })
const cluster = new CfnCluster(scope, `AtlasCluster`, {
            projectId: project.attrId,
            name: myName,
            mongoDbMajorVersion: '4.4',
        })
const dns = new CfnCustomDnsConfigurationClusterAws(scope, `AtlasClusterDns`, {
            projectId: project.attrId,
            enabled: true,
        })
cluster.node.addDependency(privateEndpoint)
dns.node.addDependency(cluster)
```

Then if I call `cluster.connectionsStrings.private` I get the `Attribute 'ConnectionStrings.Private' does not exist` error.
Just as test, I set `cluster.connectionStrings.privateEndpoint.toString()` as output of the `RootStack` it reports as undefined.
I also cannot output any element of `cluster.connectionStrings.privateEndpoint[]` which is expected at this point.

**Comment by andreaangiolillo** [comment]
Hi @mitja-hofer,

Thank you for raising the issue. We want to inform you that we have deprecated the @mongodbatlas-awscdk packages in favour of [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript) instead. This new package contains all the L1/L2 and L3 CDK constructors.

Could you try to use [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript)? Let us know if you still have the same issue.

Also, you may want to look at this similar issue [awscdk-resources-mongodbatlas#26](https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/26).

Thanks

**Comment by Zuhairahmed** [comment]
Thanks just as an update we are still review, internal ticket for tracking purposes: https://jira.mongodb.org/browse/INTMDB-818

**Comment by mitja-hofer** [comment]
Thank you for the update, I appreciate it.

**Comment by mitja-hofer** [comment]
@Zuhairahmed any updates on this or any other issues?

**Comment by Adelmar92** [comment]
Hello @mitja-hofer i see the fields you require are missing on the cloud formation resource, when you create a private endpoint i see the next fields in the cluster resource:
``` json
"awsPrivateLink": {
	"vpce-xxxxxxxxxxxxx": "mongodb://pl-1-us-east-1.4ekdo.mongodb.net:1024,pl-1-us-east-1.4ekdo.mongodb.net:1025,pl-1-us-east-1.4ekdo.mongodb.net:1026/?ssl=true&authSource=admin&replicaSet=atlas-12mwqc-shard-0",
	"vpce-yyyyyyyyyyyyy": "mongodb://pl-0-us-east-1.4ekdo.mongodb.net:1024,pl-0-us-east-1.4ekdo.mongodb.net:1025,pl-0-us-east-1.4ekdo.mongodb.net:1026/?ssl=true&authSource=admin&replicaSet=atlas-12mwqc-shard-0"
},
"awsPrivateLinkSrv": {
	"vpce-xxxxxxxxxxxxx": "mongodb+srv://cluster0-pl-1.4ekdo.mongodb.net",
	"vpce-yyyyyyyyyyyyy": "mongodb+srv://cluster0-pl-0.4ekdo.mongodb.net"
},
```

if im not wrong those are the properties you require, we might need add them the problem is that we might need to add them like this:

``` json
"awsPrivateLink": [
	"vpce-xxxxxxxxxxxxx : mongodb://pl-1-us-east-1.4ekdo.mongodb.net:1024,pl-1-us-east-1.4ekdo.mongodb.net:1025,pl-1-us-east-1.4ekdo.mongodb.net:1026/?ssl=true&authSource=admin&replicaSet=atlas-12mwqc-shard-0",
	"vpce-yyyyyyyyyyyyy : mongodb://pl-0-us-east-1.4ekdo.mongodb.net:1024,pl-0-us-east-1.4ekdo.mongodb.net:1025,pl-0-us-east-1.4ekdo.mongodb.net:1026/?ssl=true&authSource=admin&replicaSet=atlas-12mwqc-shard-0"
],
"awsPrivateLinkSrv": {
	"vpce-xxxxxxxxxxxxx : mongodb+srv://cluster0-pl-1.4ekdo.mongodb.net",
	"vpce-yyyyyyyyyyyyy : mongodb+srv://cluster0-pl-0.4ekdo.mongodb.net"
},
```
since we cannot add custom properties to the cdk resources, we might need to convert them to a list of strings. 

in the case of the privateEndpoint property is the same, but i see that the connection strings are the same so i see no point on having both

**Comment by mitja-hofer** [comment]
Hi,
I am still having issues. Calling `cluster.getAtt('ConnectionStrings.awsPrivateLinkSrv')` or `cluster.getAtt('awsPrivateLinkSrv')` fails with attribute does not exist in schema and `cluster.connectionStrings.awsPrivateLinkSrv` is undefined.
How did you get the listed fields?

**Comment by mitja-hofer** [comment]
Hi @Zuhairahmed,

I see https://jira.mongodb.org/browse/INTMDB-818 was merged and I can confirm it works in a simple setup using `Fn.select(0, cluster.getAttr('ConnectionStrings.PrivateEndpointsSrv'))`.

 I am having issues however with creating the private endpoint in some CF stack and using it in a child nested stack, since `Parameters` passed to nested stacks can only be `string` [aws docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#:~:text=%3A%20No%20interruption-,Parameters,-The%20set%20value).

Deployment then fails with `Value of property Parameters must be an object with String (or simple type) properties`.

**Comment by Adelmar92** [comment]
hello @mitja-hofer can you show me how are you passing the parameters between nested stacks?

**Comment by Zuhairahmed** [comment]
Resolving, feel free free to open new issue in case of anything else!
