### ISSUE TITLE
ProjectId field missing from CfnAlertConfigurationProps

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#558]
Hello,

I would like to report an issue I have encountered trying to set up alerts through CDK. `ProjectId` is a required field in `AlertConfiguration` however it is not part of `CfnAlertConfigurationProps` and therefore it is impossible to even deploy an AlertConfiguration through CDK.

A workaround is to use `CfnResource` provided by AWS in `aws-cdk-lib` however I don't think this is a desired solution.

Thank you very much for the time looking into this matter.

Kind Regards

**Comment by andreaangiolillo** [comment]
Hi @mitja-hofer,

Thank you for raising the issue. We want to inform you that we have deprecated [@mongodbatlas-awscdk/alert-configuration](https://www.npmjs.com/package/@mongodbatlas-awscdk/alert-configuration) and recommend using [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript) instead. This new package contains all the L1/L2 and L3 CDK constructors. 

Could you try to use [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1?lang=typescript)? Let us know if you still have the same issue.

Thanks

**Comment by mitja-hofer** [comment]
Thank you very much for the link to the new packages. It seems to work now. 

Is there maybe a communications channel where such updates are announced?

**Comment by andreaangiolillo** [comment]
Tagging @Zuhairahmed to answer this question: `Is there maybe a communications channel where such updates are announced?`

**Comment by Zuhairahmed** [comment]
Thanks @mitja-hofer, these updates were made as part of our recent GA of AWS CDK integrations with MongoDB Atlas (see [blog post ](https://www.mongodb.com/blog/post/atlas-integrations-aws-cloud-formation-cdk-now-generally-available) for more details). Going forward see updates in our our [product feedback portal](https://feedback.mongodb.com/forums/924145-atlas?category_id=392596). Hope this helps!
