### ISSUE TITLE
error creating MongoDB::Atlas::AlertConfiguration

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#559]
Hello,

I have found an issue creating AlertConfiguration using `awscdk-resources-mongodbatlas@1.0.1`. Any similar AlertConfiguration fails with `"Unable to complete request: runtime error: invalid memory address or nil pointer dereference", HandlerErrorCode: GeneralServiceException`.

I have also tested this using `CfnResource` and `type: MongoDB::Atlas::AlertConfiguration` so I am raising the issue here, since it is most probably related to the Cloudformation resources and not the MongoDB Atlas AWS CDK lib.

Example code:
```
const project = new CfnProject(scope, `AtlasProject`, {
            orgId,
            name: myProject,
        })
new CfnAlertConfiguration(scope, `${props.config.app.appName}CpuStealAbove50`, {
            profile: myProfile,
            projectId: project.attrId,
            notifications: [{
                typeName: NotificationViewTypeName.OPS_GENIE,
                opsGenieApiKey,
                delayMin: 0,
            }],
            eventTypeName: 'OUTSIDE_METRIC_THRESHOLD', 
            metricThreshold: {
                metricName: 'NORMALIZED_SYSTEM_CPU_STEAL',
                operator: MetricThresholdViewOperator.GREATER_THAN,
                threshold: 50,
                units: 'RAW',
                mode: MetricThresholdViewMode.AVERAGE,
            },
        })
```

Thank you for your time looking into this issue,
kind regards

**Comment by mitja-hofer** [comment]
Hi,
any updates on this issue?

**Comment by Adelmar92** [comment]
Hello @mitja-hofer! sorry for the delay, yes this fix is currently in Pull request, is expected to be published within this week

**Comment by Adelmar92** [comment]
hello @mitja-hofer this should have already been published, please try again with the latest version

**Comment by mitja-hofer** [comment]
Thank you for addressing this issue. I can confirm it is resolved.
