### ISSUE TITLE
Profile property should be optional for the cloud-backup-schedule resource

### ISSUE THREAD

**Issue by swachter** [mongodb/mongodbatlas-cloudformation-resources#565]
The `profile` property of the `CfnCloudBackupScheduleProps` type is required (cf.  [CfnCloudBackupScheduleProps.profile](https://github.com/mongodb/awscdk-resources-mongodbatlas/blob/main/src/l1-resources/cloud-backup-schedule/index.ts#L107). It should be optional.

I file the issue here, because I think that the TS code is derived from the model defined in this repository.

**Comment by StefanWachter1507** [comment]
bump

**Comment by andreaangiolillo** [comment]
Hi @StefanWachter1507,

Could you tell us the AWS region that you are using?  In this way, we will prioritize that region when releasing the CFN resource.

Thanks

**Comment by StefanWachter1507** [comment]
Thanks for looking into the issue. Our "main" region is "eu-central-1"

**Comment by andreaangiolillo** [comment]
Hello 👋 
We have released the fix. Make sure to activate the resource `MongoDB::Atlas::CloudBackupSchedule` `v1.2.0` and download the latest CDK version [v1.0.2](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.2?lang=java)
