### ISSUE TITLE
unable to deploy a DISK_PARTITION_UTILIZATION_DATA AlertConfiguration

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#685]
Hello,

we have a staging stack just before starting deployment mongoDB Atlas through Cloudformation to production and we can no longer update (with no changes) alert configuration of type DISK_PARTITION_UTILIZATION_DATA.
```
new CfnAlertConfiguration(scope, 'DiskUtilizationAbove90', {
      projectId,
      notifications: [{
          typeName: NotificationViewTypeName.OPS_GENIE,
          opsGenieApiKey: OpsGenieApiKey,
          delayMin: 0,
      }],
      eventTypeName: 'OUTSIDE_METRIC_THRESHOLD',
      metricThreshold: {
          metricName: 'DISK_PARTITION_UTILIZATION_DATA',
          operator: MetricThresholdViewOperator.GREATER_THAN,
          threshold: 90,
          units: 'RAW',
          mode: MetricThresholdViewMode.AVERAGE,
      },
  })
```

The error reported by Cloudformation:
```
Stack Deployments Failed: Error: The stack named mystack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "POST https://cloud.mongodb.com/api/atlas/v1.0/xxx: 400 (request "METRIC_TYPE_UNSUPPORTED") The metric type DISK_PARTITION_UTILIZATION_DATA is not supported." (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
```

This AlertConfiguration worked yesterday with no issues. The issue seems to be with MongoDB Atlas since we are seeing the same issue with our current production configuration with Terraform as outlined in the issue here: https://github.com/mongodb/terraform-provider-mongodbatlas/issues/1410 .

Thank you for looking into it.

**Comment by andreaangiolillo** [comment]
Hello @mitja-hofer 
I discussed this internally and I can confirm that this is an API change. 

Thanks

**Comment by nazarewk** [comment]
@andreaangiolillo could you share what is `DISK_PARTITION_UTILIZATION_DATA` replaced with?

**Comment by andreaangiolillo** [comment]
Hello @nazarewk 
There the metric was removed and there is no replacement metric.

Thanks
