### ISSUE TITLE
Error Running "Deploy MongoDB Atlas CloudFormation Resources"

### ISSUE THREAD

**Issue by rajeshvinayagam-lab** [mongodb/mongodbatlas-cloudformation-resources#74]
![image](https://user-images.githubusercontent.com/76505827/106217443-3c0d4c00-61a3-11eb-8e2f-8f9de9aab69c.png)

![image](https://user-images.githubusercontent.com/76505827/106217519-65c67300-61a3-11eb-84b5-b93eb8bce098.png)

**Comment by mertsaygi** [comment]
You must update boto to resolve this issue. Besides, you should add six==1.15.0 and urllib3==1.25.11 these resources to requirements.txt. It wont create your resources due to version mismatches about these packages.

**Comment by jasonmimick** [comment]
@mertsaygi -
The current Github Actions are out of date, and we are planning an update.

We have a project called [get-started-aws-cfn](https://github.com/mongodb-developer/get-started-aws-cfn) which has an updated deploy process, which I would recommend (or the real AWS MongoDB Atlas Quick Start).
