### ISSUE TITLE
Unable to complete request: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mertsaygi** [mongodb/mongodbatlas-cloudformation-resources#77]
When we change disk size of an Atlas Cluster, we got this error message:
![image](https://user-images.githubusercontent.com/5089416/112620731-f8992c00-8e39-11eb-89bd-e62f31ca8375.png)
How should we resolve this issue?

**Comment by mertsaygi** [comment]
Also, we could not update any property of db

**Comment by jasonmimick** [comment]
Hi @mertsaygi -
Thanks for reporting this. We have some major updates staged in the [https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/qs-launch-update](qs-launch-update) branch. 

Would you be able to retest your scenario with that code? 

Or you can try out the new [MongoDB Atlas on AWS](https://aws.amazon.com/quickstart/architecture/mongodb-atlas) Quick Start directly on the AWS console.

For the db properties, could you provide more details on the error and what you are trying to change?
Thanks-

**Comment by pahud** [comment]
I got the same error when I deploy the `MongoDB::Atlas::Cluster` resource type from cloudformation in `us-east-1`

<img width="894" alt="圖片" src="https://user-images.githubusercontent.com/278432/141248795-f567a82c-3181-4683-847c-97555d040519.png">

<img width="1367" alt="圖片" src="https://user-images.githubusercontent.com/278432/141248899-f6b22a0c-29c4-4a4b-896c-c6dc4f1e01fd.png">

I believe the published handler of `MongoDB::Atlas::Cluster` might have some issue or bug not being able to handle the exception. Thoughts?

**Comment by Zuhairahmed** [comment]
hi @mertsaygi @pahud we have refreshed our resources and published to AWS CFN Third Party Public Registry in all 22 AWS regions where MongoDB Atlas is currently available in. Can you double check now if this has resolved your issue?

**Comment by pahud** [comment]
Hi @Zuhairahmed 

Weird I can't find the mongo atlas AWS CFN Third Party Public Registry in the AWS CFN console any more.

**Comment by Zuhairahmed** [comment]
strange @pahud i'm not seeing any Third Party Extentions any more in the CFN Public Registry. Raised ticket with AWS and will keep you posted. 
![image](https://user-images.githubusercontent.com/47370943/210885722-e66c3325-34b4-45a0-b298-fa5f608189cc.png)

**Comment by Zuhairahmed** [comment]
@pahud Issue appears to be resolved now: 

![image](https://user-images.githubusercontent.com/47370943/210907203-63c14adf-7905-4d88-9f7d-36245279faae.png)

**Comment by pahud** [comment]
@Zuhairahmed OK I will see if I can provision the cluster through it. Probably will reach out to you privately when necessary :)

**Comment by Zuhairahmed** [comment]
sure feel free to ping me on Amazon Chime (zuhair.ahmed@mongodb.com). we are regularly work with both AWS CloudFormation and AWS CDK engineering teams on our product roadmap/updates. happy to share anything else you need @pahud.

**Comment by Zuhairahmed** [comment]
Closing this issue @pahud, but feel free to reach out if you need anything else.
