### ISSUE TITLE
Mongo Atlas Project fails creation

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/mongodbatlas-cloudformation-resources#847]
Hello,

a MongoDB Atlas project creation failed with `"Failed to Create Project : https://cloud.mongodb.com/api/atlas/v2/groups POST: HTTP 409 Conflict (Error code: "GROUP_ALREADY_EXISTS") Detail: A group with name xxxxx already exists. Reason: Conflict. `

We saw on the MongoDB Atlas that the project was created at 2:24:19 PM and got the error at 2:24:30 PM. We assume a create project request to Atlas succeeded but was not reported to Cloudformation at was therefore retried. The request then failed and broke our entire Cloudformation Stack deployment. 

We do not have access to any more logs than what I described above.

Thank you for looking into it.

**Comment by Zuhairahmed** [comment]
Thanks for reporting @mitja-hofer. This type of error occurs when attempting to create an Atlas Project when one with same Project Name already existing in your Atlas Organization. For more details see - https://www.mongodb.com/docs/atlas/reference/api-errors/#mongodb-apierror-GROUP_ALREADY_EXISTS
