### ISSUE TITLE
AWS default profile in config files

### ISSUE THREAD

**Issue by SmutsMuts** [mongodb/mongodbatlas-cloudformation-resources#92]
### Steps to Reproduce
I am trying to clone and run this repository to execute the cfn-submit-helper.sh file to register all the resources in our aws account. When I run this repo in my Azure DevOps pipeline I get an error because in all the config files there is a default profile set to "711489243244_AdministratorAccess" and I can't see any way of sending a different profile as a parameter to the .sh file.
I think there should be a parameter to the script-file and there maybe shouldn't be any hard-coded default profile checked in to the repo?

### Reference
[mongodbatlas-cloudformation-resources](https://github.com/mongodb/mongodbatlas-cloudformation-resources)/[cfn-resources](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/cfn-resources)/cfn-submit-helper.config
export CFN_SUBMIT_LOG_LEVEL=info
export CFN_SUBMIT_CFN_FLAGS="--verbose --set-default"
export AWS_DEFAULT_PROFILE=711489243244_AdministratorAccess

**Comment by Zuhairahmed** [comment]
Hi @SmutsMuts looking at code base in https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/cfn-submit-helper.sh appears now that default AWS profile has been removed. can you confirm if this issue has been resolved on your end?
