### ISSUE TITLE
Can't set up Auto Scaling with Cluster resource

### ISSUE THREAD

**Issue by tnation14** [mongodb/mongodbatlas-cloudformation-resources#94]
Hi, 

I'm having an issue creating an Atlas cluster with autoscaling enabled. Given the below resource definition, I get a 400 error with the message `Compute auto-scaling min instance size required.`. However, if I specify `AutoScaling.Compute.MaxInstanceSize` and/or `AutoScaling.Compute.MinInstanceSize` in my resource definition, I get another error saying `Invalid attribute minInstanceSize specified.` Is Cluster Tier scaling supported, and if so, do y'all have a working example? Thanks in advance.

## Code snippet
```json
  "OrganizerServicesTestInstanceAtlasClsutertestinstance543CDFC6": {
   "Type": "MongoDB::Atlas::Cluster",
   "Properties": {
    "ApiKeys": {
     "PublicKey": "<REDACTED>",
     "PrivateKey": "<REDACTED>"
    },
    "ProjectId": {
     "Ref": "OrganizerServicesAtlasProjectAtlasProjectsandboxE89594CB"
    },
    "Name": "test-instance",
    "MongoDBMajorVersion": "5.0",
    "ProviderSettings": {
     "BackingProviderName": "AWS",
     "InstanceSizeName": "M10",
     "RegionName": "us-east-1",
     "AutoScaling": {
      "Compute": {
       "Enabled": true,
       "ScaleDownEnabled": true,
       "MinInstanceSize": "M10",
       "MaxInstanceSize": "M50"
      }
     }
    },
    "AutoScaling": {
     "Compute": {
      "Enabled": true,
      "ScaleDownEnabled": true
     }
    }
   },
   "DependsOn": [
    "OrganizerServicesAtlasProjectAtlasProjectsandboxE89594CB"
   ],
   "Metadata": {
    "aws:cdk:path": "OrganizerServicesInfrastructureStack-sandbox/OrganizerServicesTestInstance/AtlasClsuter-test-instance"
   }
  },
```

## Expected Behavior
200 response, cluster created with cluster tier scaling enabled.

## Actual behavior
400, `Compute auto-scaling min instance size required.` if `AutoScaling.Compute.MinInstanceSize` is not set,
400,  `Invalid attribute minInstanceSize specified.` if `AutoScaling.Compute.MinInstanceSize` is set.

**Comment by zions-griiip** [comment]
I've encountered the same issue!

**Comment by Zuhairahmed** [comment]
@tnation14 / @zions-griiip can you confirm if this fix has resolved your issue?

**Comment by tnation14** [comment]
Will give it a shot and let you know. Thank you!

**Comment by Zuhairahmed** [comment]
Closing due to lack activity, feel free to re-open if you need anything else!
